cm:
  name: chenmin
  birthday: 19950808
  total: ${cm.name}+++++++++++++++++${cm.birthday}

spring:
  profiles:
    active: ttt
    include: test,devDB

#  path: /var/my.log
logging:
  config: classpath:logback-spring.xml
#  file: my.log
#  level:
#      hello: trace



