#development environment
#spring:
#profiles: dev
server:
  port: 8080

#spring:
#  profiles:
#    active: devDB
spring:
  datasource:
    url: jdbc:mysql://139.155.78.92:3306/springBoot?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Cm950808.
    driver-class-name: com.mysql.jdbc.Driver


